name: Publish Auction Backend Docker Image

on:
  workflow_run:
    workflows: [ Release Auction REST API ]
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    name: Publish Auction Backend Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: 'x64'

      - name: 'Build project with Maven'
        run: |
          mvn verify -DskipTests

      - name: Get version
        id: get_version
        run: |
          chmod +x get_version.sh
          echo "version=$(./get_version.sh)" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Publish Auction Database Docker Image'
        working-directory: ${{ github.workspace }}/db
        run: |
          docker build . -t ghcr.io/phuuthanh2003/auction-database:${{ steps.get_version.outputs.version }} -t ghcr.io/phuuthanh2003/auction-database:latest
          docker push ghcr.io/phuuthanh2003/auction-database:${{ steps.get_version.outputs.version }}
          docker push ghcr.io/phuuthanh2003/auction-database:latest


      - name: 'Publish Auction Backend Docker Image'
        working-directory: ${{ github.workspace }}/server
        run: |
          docker build . -t ghcr.io/phuuthanh2003/auction-api:${{ steps.get_version.outputs.version }} -t ghcr.io/phuuthanh2003/auction-api:latest
          docker push ghcr.io/phuuthanh2003/auction-api:${{ steps.get_version.outputs.version }}
          docker push ghcr.io/phuuthanh2003/auction-api:latest